### ISSUE TITLE
Environment not needed?

### ISSUE THREAD

**Issue by MarieSaphira** [typhon-project/typhon-polystore-ui#4]
Since the UI got changed, it always uses `typhon-polystore-service:8080` as API address right? So we could remove the environment from the UI containers? Giving the API host during DL modeling time is not that great, so I think removing the environment would improve the overall experience.

**Comment by Stratidakos** [comment]
The UI won't work unless it knows directly the API's host and port. That is, because we made a few optimization changes to the UI, in order for it to start immediately. So, no it can't be removed.

**Comment by MarieSaphira** [comment]
Yes, but with your changes the UI doesn't have to access the API "from outside" (as before), right? The API and the UI will always be deployed alongside, that means in the same network. Due to docker and kubernetes service discovery you could change [this line](https://github.com/typhon-project/typhon-polystore-ui/blob/7cf8396f74142e0ce79d3ad9e1364e2b5b6a0550/docker/default.conf.template#L2):
```
server ${API_HOST}:${API_PORT};
```
to 
```
typhon-polystore-service:8080;
```

**Comment by theofilis** [comment]
Sorry, we can't change this options because it helps us with testing. 

So we still have to define this two Enviroments Variable.

**Comment by DavyLandman** [comment]
I assume you run the node dev server for testing? Can't you special case something there? like by default it goes to the reverse proxy but in dev it goes to an env variable? 

That would make the nginx config simpler and only correct for deploy setup?

**Comment by MarieSaphira** [comment]
I will leave it in the deployment scripts but will hide it from the user then.

**Comment by theofilis** [comment]
@MarieSaphira, I agree with this. User doesn't need to be aware of this option.
